### ISSUE TITLE
Development Group's invite link is broken?

### ISSUE THREAD

**Issue by ghost** [SEEDTEAM/TeleSeed#194]
It called me "This link is invaild or expried" when I Open https://telegram.me/joinchat/B6GrdT5v9Vn5Ib0qlMvIBw .

Here is Telegram Web's tech info.

Method: messages.checkChatInvite
Url: N/A
Result: {"_":"rpc_error","error_code":400,"error_message":"INVITE_HASH_EXPIRED"}
Stack: Error
    at Object.h [as invokeApi](https://web.telegram.org/js/app.js:23:25735)
    at v (https://web.telegram.org/js/app.js:25:31282)
    at g (https://web.telegram.org/js/app.js:25:28732)
    at m (https://web.telegram.org/js/app.js:25:28121)
    at Object.f [as start](https://web.telegram.org/js/app.js:25:31073)
    at new <anonymous> (https://web.telegram.org/js/app.js:26:13653)
    at Object.r [as instantiate](https://web.telegram.org/js/app.js:11:21370)
    at https://web.telegram.org/js/app.js:12:15279
    at Object.link (https://web.telegram.org/js/app.js:16:12334)
    at https://web.telegram.org/js/app.js:11:6148

**Comment by ghost** [comment]
> Join our bot development group by sending /join 56670147 to @TeleSeed

May be your website change invitation link to readme.md's this section?

**Comment by TiagoDanin** [comment]
@Imandaneshi 
URL for the channel also is broke
